version: "3"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - my_network
  wordpress:
    container_name: wordpress
    build:
        context: ./requirements/wordpress
        dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - my_network
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html/wordpress
    networks:
      - my_network
volumes:
  mariadb:
  wordpress:
networks:
  my_network:
    driver: bridge